Ecommerce/Ecommerce/Models/ErrorViewModel.cs
using System;

namespace Ecommerce.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Ecommerce/Ecommerce/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Ecommerce.Models;
using Microsoft.AspNetCore.Http;


namespace Ecommerce.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewBag.User = HttpContext.Session.GetString("user");
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Ecommerce/Ecommerce/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DAL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace Ecommerce.Controllers
{
    public class LoginController : Controller
    {
        private IWebHostEnvironment Environment;
        public LoginController(IWebHostEnvironment _environment)
        {
            Environment = _environment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(new Customer());
        }

        [HttpPost]
        public IActionResult Index(Customer customer)
        {
            DAL.AppContext appContext = new DAL.AppContext();
            Customer customerDatabase = appContext.Customers
                .Where(x => x.Email == customer.Email).SingleOrDefault();
            if (customerDatabase == null)
            {
                ViewBag.Error = "Usuário ou senha incorretos!";
                return View(customer);
            }
            else
            {
                string hash = customer.Hash + customerDatabase.Salt;
                hash = Util.Cryptography.CreateMD5(hash);
                if (customerDatabase.Hash == hash)
                {
                    HttpContext.Session.SetString("user", customerDatabase.Name);
                    HttpContext.Session.SetInt32("userId", customerDatabase.Id);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.Error = "Usuário ou senha incorretos!";
                    return View(customer);
                }
            }
        }

        [HttpPost]
        public IActionResult Create(Customer customer, IFormFile postedFile)
        {
            if (postedFile != null && postedFile.Length > 0) //arquivo não está vazio
            {
                string wwwPath = this.Environment.WebRootPath;
                string contentPath = this.Environment.ContentRootPath;

                string path = Path.Combine(this.Environment.WebRootPath, "Uploads");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                string fileName = Path.GetFileName(postedFile.FileName);
                using (FileStream stream = new FileStream(Path.Combine(path, fileName), FileMode.Create))
                {
                    postedFile.CopyTo(stream);
                    customer.Picture = fileName;
                }
            }
            DAL.AppContext appContext = new DAL.AppContext();
            customer.Salt = Guid.NewGuid().ToString();
            customer.Hash = Util.Cryptography.CreateMD5(customer.Hash + customer.Salt);
            appContext.Customers.Add(customer);
            appContext.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
}

Ecommerce/Ecommerce/Controllers/ProductController.cs
using DAL;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Ecommerce.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult Index(int? categoryId)
        {
            DAL.AppContext contexto = new DAL.AppContext();
            IEnumerable<Product> lsProducts = contexto.Products;
            if (categoryId.HasValue)
            {
                lsProducts = lsProducts.Where(x => x.CategoryId == categoryId.Value);
            }
            lsProducts = lsProducts.OrderBy(x => x.Name).ToList();
            ViewBag.Categories = contexto.Categories.OrderBy(x => x.Name).ToList();
            return View(lsProducts);
        }

        public IActionResult Detail(int id)
        {
            DAL.AppContext context = new DAL.AppContext();
            Product product = context.Products.Find(id);
            return View(product);
        }
    }
}

Ecommerce/Ecommerce/Controllers/ProdutoController.cs
using DAL;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace Ecommerce.Controllers
{
    public class ProdutoController : Controller
    {
        public IActionResult Index()
        {
            Contexto contexto = new Contexto();

            //Produto novoProduto = new Produto();
            //novoProduto.Name = "Novo ";
            //novoProduto.Price = DateTime.Now.Second;
            //contexto.Produtos.Add(novoProduto);
            //contexto.SaveChanges();

            var lsProdutos = contexto.Produtos.OrderBy(x => x.Name).ToList();
            return View(lsProdutos);
        }
    }
}

Ecommerce/Ecommerce/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem-vindo @ViewBag.User</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Ecommerce/Ecommerce/Views/Login/Index.cshtml
@model DAL.Customer

<h1>Acesse sua conta</h1>

<div class="row">
    <div class="col-6">
        <h2>Já tenho uma conta</h2>
        <form method="post">
            <div class="form-group">
                <label for="user">Usuário</label>
                <input type="email" class="form-control" id="user" name="Email" />
            </div>
            <div class="form-group">
                <label for="pass">Senha</label>
                <input type="password" class="form-control" id="pass" name="Hash" />
            </div>
            <button class="btn btn-dark">Acessar</button>
            @if(ViewBag.Error != null)
            {
                <div class="alert alert-danger mt-3">@ViewBag.Error</div>
            }
        </form>
    </div>
    <div class="col-6">
        <h2>Criar uma nova conta</h2>
        <form method="post" enctype="multipart/form-data" action="@Url.Action("Create")">
            <div class="form-group">
                <label for="name">Nome</label>
                <input type="text" class="form-control" id="name" name="Name" />
            </div>
            <div class="form-group">
                <label for="email">E-mail</label>
                <input type="text" class="form-control" id="email" name="Email" />
            </div>
            <div class="form-group">
                <label for="doc">Documento</label>
                <input type="text" class="form-control" id="doc" name="Document" />
            </div>
            <div class="form-group">
                <label for="pass">Senha</label>
                <input type="password" class="form-control" id="pass" name="Hash" />
            </div>
            <div class="form-group">
                <label for="image">Imagem</label>
                <input type="file" class="form-control" id="image" name="postedFile" />
            </div>

            <button class="btn btn-dark">Criar Conta</button>
        </form>
    </div>
</div>

Ecommerce/Ecommerce/Views/Product/Detail.cshtml
@model DAL.Product
@{
}

<h1>@Model.Name</h1>
<code>@Model.Category.Name</code>

@Html.Raw(Model.Description)

Ecommerce/Ecommerce/Views/Product/Index.cshtml
@model List<DAL.Product>
@{
    ViewData["Title"] = "Index";
    List<DAL.Category> Categories = ViewBag.Categories;
}

<h1>Listando Produtos (@Model.Count)</h1>

<div class="btn-group mb-4" role="group">
    <a class="btn btn-secondary" href="@Url.Action("Index", "Product")">Todos</a>
    @foreach (var category in Categories)
    {
        <a href="@Url.Action("Index", "Product", new { categoryId = category.Id } )" class="btn btn-secondary">
            @category.Name
        </a>
    }
</div>

<div class="row">
    @foreach (var product in Model)
    {
        <div class="col-3 mb-3">
            <a class="card d-block" href="@Url.Action("Detail", "Product", new { Id = product.Id })">
                <span class="card-body d-block">
                    <img src="@product.Image" />
                    @product.Name (@product.Category.Name)
                </span>
            </a>
        </div>
    }
</div>

Ecommerce/Ecommerce/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor

@{ 
    string userName = HttpContextAccessor.HttpContext.Session.GetString("user");
}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ecommerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ecommerce</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li>
                            <a class="nav-link" href="@Url.Action("Index", "Product")">Produtos</a>
                        </li>
                    </ul>
                    <span class="navbar-text">
                        @if(userName != null && userName != "")
                        {
                            <span>Olá @userName</span>
                        }
                        else
                        {
                            <a href="@Url.Action("Index", "Login")" class="btn btn-primary">Login</a>
                        }
                    </span>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Ecommerce - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>